services:
  nginx:
    volumes:
      - ./nginx/webroot:/var/www/certbot:ro
      - certbot-certs:/etc/letsencrypt:ro

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - certbot-certs:/etc/letsencrypt
      - ./nginx/webroot:/var/www/certbot
    command: ["--version"]
    networks:
      - noot-not-network

volumes:
  certbot-certs:

networks:
  noot-not-network:
    driver: bridge
