version: '3.8'

services:
  nginx:
    volumes:
      - ./nginx/webroot:/var/www/certbot:ro
      - certbot-certs:/etc/letsencrypt:ro
      - certbot-www:/var/www/certbot:ro

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - certbot-certs:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    command: certbot --version
    profiles:
      - tools

volumes:
  certbot-certs:
  certbot-www:
