version: '3.8'

services:
  frontend:
    build: .
    container_name: noot-not-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api
    networks:
      - noot-not-network

networks:
  noot-not-network:
    external: true
