version: "3.8"

services:
  frontend:
    build:
      context: .
      args:
        VITE_API_BASE_URL: https://api.nootnot.rocks/api
    container_name: noot-not-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - noot-not-network

networks:
  noot-not-network:
    external: true
