version: "3.8"

services:
  app:
    build: .
    container_name: noot-not-api
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=noot_not
      - DB_USER=noot_user
      - DB_PASSWORD=noot_password
      - IMAGE_API_URL=https://image-api.nootnot.rocks
    volumes:
      - ./public/images:/var/www/public/images
    depends_on:
      - db
    networks:
      - noot-not-network

  db:
    image: mariadb:10.6
    container_name: noot-not-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: noot_not
      MYSQL_USER: noot_user
      MYSQL_PASSWORD: noot_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - noot-not-network

volumes:
  db_data:

networks:
  noot-not-network:
    driver: bridge
